apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elevate-chatbot.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  DATABASE_URL: {{ .Values.environment.backend.DATABASE_URL | quote }}
  BACKEND_URL: {{ .Values.environment.mcpServer.BACKEND_URL | quote }}
  FRONTEND_URL: {{ .Values.environment.mcpServer.FRONTEND_URL | quote }}
  DEBUG: {{ .Values.environment.backend.DEBUG | quote }}