apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elevate-chatbot.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- if .Values.global.storageClass }}
{{- if (ne .Values.global.storageClass "default") }}
  storageClassName: {{ .Values.global.storageClass }}
{{- end }}
{{- end }}